#!/bin/tcsh
#PBS -N BigRailRunClunk
#PBS -l nodes=30:bora:ppn=20
#PBS -l walltime=72:00:00
#PBS -k oe


cd $PBS_O_WORKDIR

conda activate mpi
mpiexec -np 600 python3 -u Rail-clunkLockBigRun15x.py >& TryBigRun-240205.out
