#!/bin/tcsh
#PBS -N Drop4m
#PBS -l nodes=40:bora:ppn=20
#PBS -l walltime=72:00:00
#PBS -k oe


cd $PBS_O_WORKDIR

conda activate mpi
mpiexec -np 800 python3 -u Rail-slap-WheelLoad.py >& Drop-11-01-1300.out
