#!/bin/tcsh
#PBS -N RailSRbig
#PBS -l nodes=6:bora:ppn=20
#PBS -l walltime=72:00:00
#PBS -k oe


cd $PBS_O_WORKDIR

conda activate mpi
mpiexec -np 32 -rr python3 -u stressMPI-Rail.py >& SRbig-0614-1300.out
