#!/bin/tcsh
#PBS -N RodShearNB
#PBS -l nodes=1:hima:ppn=64
#PBS -l walltime=72:00:00
#PBS -k oe


cd $PBS_O_WORKDIR

conda activate mpi
mpiexec -np 60 -rr python3 -u stressMPI-cube-acu.py >& CubeSherNB-0723-1555.out
