#!/bin/tcsh
#PBS -N CubeShearNB
#PBS -l nodes=1:hima:ppn=32
#PBS -l walltime=72:00:00
#PBS -k oe


cd $PBS_O_WORKDIR

conda activate mpi
mpiexec -np 30 -rr python3 -u stressMPI-cube-acu.py >& CubeAcuNB-0627-0910.out
