#!/bin/tcsh
#PBS -N Clean20m10XRfRq
#PBS -l nodes=1:hima:ppn=32
#PBS -l walltime=72:00:00
#PBS -j oe
#PBS -m abe

cd $PBS_O_WORKDIR

conda activate mpi
python3 makePicklesFromPickles.py >& PickleMaking-240119.out